environment:
  matrix:
  - nodejs_version: "6.9"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm test

build: off